'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CalculatedFieldsInServerModeWebForms


	Partial Public Class [Default]

		''' <summary>
		''' form1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

		''' <summary>
		''' GridView control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected GridView As Global.DevExpress.Web.ASPxGridView

		''' <summary>
		''' EntityServerModeDataSource1 control.
		''' </summary>
		''' <remarks>
		''' Auto-generated field.
		''' To modify move field declaration from designer file to code-behind file.
		''' </remarks>
		Protected EntityServerModeDataSource1 As Global.DevExpress.Data.Linq.EntityServerModeDataSource
	End Class
End Namespace
