//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatedFieldsInServerModeWebForms.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CalculatedFieldsTestEntities : DbContext
    {
        public CalculatedFieldsTestEntities()
            : base("name=CalculatedFieldsTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Product> Products { get; set; }
    
        [DbFunction("CalculatedFieldsTestEntities", "CustomProducts")]
        public virtual IQueryable<CustomProducts_Result> CustomProducts(Nullable<int> daysExpiresOffset, Nullable<System.DateTime> currentDate)
        {
            var daysExpiresOffsetParameter = daysExpiresOffset.HasValue ?
                new ObjectParameter("daysExpiresOffset", daysExpiresOffset) :
                new ObjectParameter("daysExpiresOffset", typeof(int));
    
            var currentDateParameter = currentDate.HasValue ?
                new ObjectParameter("currentDate", currentDate) :
                new ObjectParameter("currentDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<CustomProducts_Result>("[CalculatedFieldsTestEntities].[CustomProducts](@daysExpiresOffset, @currentDate)", daysExpiresOffsetParameter, currentDateParameter);
        }
    }
}
