Imports System.Linq
Imports System.Data.Entity.Core.Objects
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CalculatedFieldsInServerModeWebForms.Model

	Partial Public Class CalculatedFieldsTestEntities
		Inherits DbContext

		Public Sub New()
			MyBase.New("name=CalculatedFieldsTestEntities")
		End Sub

		Protected Overrides Sub OnModelCreating(ByVal modelBuilder As DbModelBuilder)
			Throw New UnintentionalCodeFirstException()
		End Sub

		Public Overridable Property Products() As DbSet(Of Product)

		<DbFunction("CalculatedFieldsTestEntities", "CustomProducts")>
		Public Overridable Function CustomProducts(ByVal daysExpiresOffset? As Integer, ByVal currentDate? As DateTime) As IQueryable(Of CustomProducts_Result)
			Dim daysExpiresOffsetParameter = If(daysExpiresOffset.HasValue, New ObjectParameter("daysExpiresOffset", daysExpiresOffset), New ObjectParameter("daysExpiresOffset", GetType(Integer)))

			Dim currentDateParameter = If(currentDate.HasValue, New ObjectParameter("currentDate", currentDate), New ObjectParameter("currentDate", GetType(DateTime)))

			Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of CustomProducts_Result)("[CalculatedFieldsTestEntities].[CustomProducts](@daysExpiresOffset, @currentDate)", daysExpiresOffsetParameter, currentDateParameter)
		End Function
	End Class
End Namespace
