Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace CalculatedFieldsInServerModeWebForms.Model

	Partial Public Class Product
		Public Property Id() As Integer
		Public Property ProductName() As String
		Public Property ProductPrice() As Decimal
		Public Property UnitsInStock() As Integer
		Public Property ProductionDate() As DateTime
	End Class
End Namespace
